development: 
  stripe:
    secret_key: sk_test_RxAGQjjnY308ZUlfGxzOLxM5
    publishable_key: pk_test_IT88iPGjeTM3bQKNQUG7kALn

test: 
  stripe:
    secret_key: sk_test_RxAGQjjnY308ZUlfGxzOLxM5
    publishable_key: pk_test_IT88iPGjeTM3bQKNQUG7kALn

production:
  stripe:
    secret_key: sk_test_RxAGQjjnY308ZUlfGxzOLxM5
    publishable_key: pk_test_IT88iPGjeTM3bQKNQUG7kALn
